apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: pv-deploy
  name: pv-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pv-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pv-deploy
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - image: nginx:stable
        name: pv-deploy
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: task-pv-storage


        resources: {}
status: {}
